apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-manager.fullname" . }}
  labels:
    {{- include "core-manager.labels" . | nindent 4 }}
  automountServiceAccountToken: true
