parameters:
  - name: serviceConnection
    type: string
    displayName: "The service connection"

  - name: envShortCode
    type: string
    displayName: "The short code for the environment (dev/qa/stage)"

  - name: buildagent
    type: string
    displayName: "Build Agent name"
    default: "IAA-Buildagent"

  - name: environment
    type: string
    displayName: "Environment"

  - name: acrname
    type: string
    displayName: "ACR name"

  - name: modelregistry
    type: string
    displayName: "model registry name"
    default: "alpine"

  - name: modeltag
    type: string
    displayName: "model tag (version)"
    default: "latest"

  - name: buildid
    type: string
    displayName: "Build number"

jobs:
  - deployment: ${{ parameters.envShortCode }}_deployment
    pool:
      name: HDP Image Analyzer Application Agent
      demands:
        - agent.name -equals ${{ parameters.buildagent }}
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            #dev acr Login using Service principal
            - task: Docker@2
              displayName: Login to ACR
              inputs:
                containerRegistry: ${{parameters.serviceConnection}}
                command: "login"

            #image push to private ACR
            - task: CmdLine@2
              inputs:
                script: |
                  docker image tag acrpubmlwscicdweus.azurecr.io/${{parameters.modelregistry}}:${{parameters.modeltag}}_${{parameters.buildid}} ${{parameters.acrname}}.azurecr.io/${{parameters.modelregistry}}:${{parameters.modeltag}}_${{parameters.buildid}}
                  docker image push ${{parameters.acrname}}.azurecr.io/${{parameters.modelregistry}}:${{parameters.modeltag}}_${{parameters.buildid}}
                  docker images
                  docker image inspect ${{parameters.acrname}}.azurecr.io/${{parameters.modelregistry}}:${{parameters.modeltag}}_${{parameters.buildid}}
