# Plans for all states on the QA environment.

name: $(Date:yyyyMMdd)$(Rev:.r)-infrastructure-plan-qa

trigger: none

stages:
  - stage: check_terraform
    displayName: Check Terraform
    jobs:
      - template: templates/jobs/checkov-template.yaml
        parameters:
          dir: "$(System.DefaultWorkingDirectory)"
          failOnSecret: true
  - template: "templates/stages/plan-states-template.yaml"
    parameters:
      envShortCode: "qa"
      validate: true
