pool:
  name: HDP Image Analyzer Application Agent
  demands:
    - agent.name -equals IAA-BuildAgent

trigger: none

parameters:
  - name: registryType
    default: private
    displayName: Container Registry Type
    values:
      - private
      - public
  - name: envShortCode
    default: dev
    displayName: Environment
    values:
      - dev
      - qa
      - stage
  - name: imageRepository
    default: aixs-usecase-maringa
    displayName: Repo Name

variables:
  - name: azureSubscription
    ${{ if or(eq( parameters['envShortCode'], 'dev'),eq( parameters['envShortCode'], 'qa')) }}:
      value: "sp-iaa-tf-serviceconnection"
    ${{ else }}:
      value: "sp-iaa-${{ parameters.envShortCode }}-tf-serviceconnection"
  - name: azureContainerRegistry
    ${{ if eq( parameters['registryType'], 'private') }}:
      value: "acrmlws${{ parameters.envShortCode }}weus"
    ${{ else }}:
      value: "acrpubmlwscicdweus"
  - name: resourceGroup
    ${{ if eq( parameters['registryType'], 'private') }}:
      value: "kv-mlws-${{ parameters.envShortCode }}-weus"
    ${{ else }}:
      value: "kv-cicd-weus-buildagent"

stages:
  - stage: CreateAcrPasswords
    jobs:
      - job: acrPasswordCreation
        steps:
          - task: AzureCLI@2
            displayName: Azure CLI
            inputs:
              azureSubscription: ${{ variables.azureSubscription }}
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "deployment/azure-pipelines/global/scripts/create-passwords-for-acr-tokens.sh"
              arguments: "-a ${{ variables.azureContainerRegistry }} -v ${{ variables.resourceGroup }} -r ${{ parameters.imageRepository }}"
