# Stage template runs plan for kubernetes state and is parameterized by environment.
parameters:
  - name: envShortCode
    type: string
    displayName: "Environment of the job (short code format: dev/qa/stage/prod)"
    default: "dev"
    values:
      - dev
      - qa
      - stage
      - prod
      - pen
  - name: validate
    type: boolean
    displayName: "Run terraform validate or not."
    default: false
  - name: dependson
    type: string
    displayName: "Stage Dependencies."
    default: ""

stages:
  - stage: terraform_plan_${{ parameters.envShortCode }}_customconfig
    displayName: "Plan - ${{ parameters.envShortCode }} - customconfig"
    variables:
      - template: "../../vars/${{ parameters.envShortCode }}-vars.yaml"
    jobs:
      - template: "../jobs/infra-plan-template.yaml"
        parameters:
          envShortCode: ${{ parameters.envShortCode }}
          subscriptionShortCode: "${{ variables.subscriptionShortCode }}"
          stateFile: "${{ variables.stateFilecustomconfig }}"
          workDir: "$(System.DefaultWorkingDirectory)"
          buildId: "$(Build.BuildId)"
          pathToTFCode: "infrastructure/customconfig"
          buildAgentName: "${{ variables.selfBuildAgentName }}"
          stateDisplayName: "customconfig"
