apiVersion: v1
kind: Secret
metadata:
  name: dapr-secret
data:
  azureClientSecret: {{ .Values.daprSecrets.azureClientSecret | toString | b64enc }}
  azureClientId: {{ .Values.daprSecrets.azureClientId | toString | b64enc }}
  azureTenantId: {{ .Values.daprSecrets.azureTenantId | toString | b64enc }}