apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-manager.fullname" . }}
  labels:
    {{- include "ai-manager.labels" . | nindent 4 }}
    {{- with .Values.service.annotations }}
  annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-manager.selectorLabels" . | nindent 4 }}
