repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "^.+jsonl$"
      - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        pass_filenames: true
        always_run: true
        language: python
        types: [python]
        args: ["--line-length=120"]
    require_serial: true
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "--fail-under=6",
            "--max-line-length=120",
          ]
        always_run: true
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.0
  #   hooks:
  #     - id: flake8
# "--rcfile=.pylintrc", # Link to your config file
