apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
data:
  CONFIG_TENANT_ID: {{ .Values.envSecrets.CONFIG_TENANT_ID | toString | b64enc }}
  CONFIG_CLIENT_APP_ID: {{ .Values.envSecrets.CONFIG_CLIENT_APP_ID | toString | b64enc }}
  CONFIG_SECRET_ID: {{ .Values.envSecrets.CONFIG_SECRET_ID | toString | b64enc }}
  CONFIG_API_APP_ID: {{ .Values.envSecrets.CONFIG_API_APP_ID | toString | b64enc }}
  CONFIG_SUBSCRIPTION_KEY: {{ .Values.envSecrets.CONFIG_SUBSCRIPTION_KEY | toString | b64enc }}
  CONFIG_TARGET_TENANT_ID: {{ .Values.envSecrets.CONFIG_TARGET_TENANT_ID | toString | b64enc }}