kind: Deployment
apiVersion: apps/v1
metadata:
  name: carin-model-oct
  # CKV_K8S_21: "The default namespace should not be used"
  namespace: iaa
  labels:
    app: carin-model-oct
  annotations:
    # suppressing rule not applicable
    checkov.io/skip1: CKV_K8S_8=disabling liveness probe check since http/tcp path for health check is not known
    checkov.io/skip2: CKV_K8S_9=disabling rediness probe check since http/tcp path for health check is not known
    checkov.io/skip3: CKV_K8S_43=Ignoring Image should use digest
    checkov.io/skip4: CKV_K8S_14=Ignoring Image Tag should be fixed - not latest or blank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carin-model-oct
  template:
    metadata:
      labels:
        app: carin-model-oct
    spec:
      # CKV_K8S_29: "Apply security context to your pods and containers"
      # CKV_K8S_23: "Minimize the admission of root containers"
      # CKV_K8S_40: "Containers should run as a high UID to avoid host conflict"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
      # CKV_K8S_38: "Ensure that Service Account Tokens are only mounted where necessary"
      automountServiceAccountToken: false
      nodeSelector:
        agentpool: linuxcpu
      containers:
        - name: carin-model-oct
          image: acrmlwsdevweus.azurecr.io/oct_image_analyzer:latest
          # CKV_K8S_15: "Image Pull Policy should be Always"
          imagePullPolicy: Always
          # CKV_K8S_20: "Containers should not run with allowPrivilegeEscalation"
          # CKV_K8S_22: "Use read-only filesystem for containers where possible"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
                - ALL
          # CKV_K8S_11: "CPU limits should be set"
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m
          # livenessProbe:
          #   httpGet:
          #     path: /octmodel/health
          #     port: 80
          #   initialDelaySeconds: 45
          #   periodSeconds: 30
          #   timeoutSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /octmodel/health
          #     port: 80
          #   initialDelaySeconds: 45
          #   periodSeconds: 30
          #   timeoutSeconds: 3
          # resources:
          #   limits:
          #     cpu: 300m
          #   requests:
          #     cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: carin-model-oct-lb
  # CKV_K8S_21: "The default namespace should not be used"
  namespace: iaa
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: carin-model-oct
