apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-data-access
  # CKV_K8S_21: "The default namespace should not be used"
  namespace: iaa
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dd448f5c-c503-4a4d-bef1-13797be04287"
    keyvaultName: "kv-mlws-dev-weus"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: kv-vm-mlws-dev-buldagent
          objectType: secret
          objectVersion: ""

    resourceGroup: "rg-mlw-dev-weus"
    subscriptionId: "1fb500bc-6cb9-4087-97f0-8cc28b82ae40"
    tenantId: "82913d90-8716-4025-a8e8-4f8dfa42b719"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odx-model-bscani
  name: odx-model-bscani
  # CKV_K8S_21: "The default namespace should not be used"
  namespace: iaa
  annotations:
    # suppressing rule not applicable
    checkov.io/skip1: CKV_K8S_8=disabling liveness probe check since http/tcp path for health check is not known
    checkov.io/skip2: CKV_K8S_9=disabling rediness probe check since http/tcp path for health check is not known
    checkov.io/skip3: CKV_K8S_43=Ignoring Image should use digest
    checkov.io/skip4: CKV_K8S_14=Ignoring Image Tag should be fixed - not latest or blank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odx-model-bscani
  template:
    metadata:
      labels:
        app: odx-model-bscani
    spec:
      # CKV_K8S_29: "Apply security context to your pods and containers"
      # CKV_K8S_23: "Minimize the admission of root containers"
      # CKV_K8S_40: "Containers should run as a high UID to avoid host conflict"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
      # CKV_K8S_38: "Ensure that Service Account Tokens are only mounted where necessary"
      automountServiceAccountToken: false
      nodeSelector:
        agentpool: wincpu
      containers:
        - name: odx-model-bscani
          image: acrmlwsdevweus.azurecr.io/bsi:v2
          # CKV_K8S_15: "Image Pull Policy should be Always"
          imagePullPolicy: Always
          # CKV_K8S_20: "Containers should not run with allowPrivilegeEscalation"
          # CKV_K8S_22: "Use read-only filesystem for containers where possible"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - NET_RAW
                - ALL
          # CKV_K8S_11: "CPU limits should be set"
          # CKV_K8S_10: "CPU requests should be set"
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: PubSubName
              value: pubsubazuresb
            - name: TableName
              value: tblsgmlifdevweus

          #image: nginx
          volumeMounts:
            - mountPath: /SharedVolume
              name: odx-model-bscani-volume
            - mountPath: /kvmount
              name: secrets-store-data-access
              # - mountPath: /usr/share/nginx/html
              #   name: odx-model-bscani-pv-storage
      volumes:
        # - name: odx-model-bscani-pv-storage
        #   persistentVolumeClaim:
        #     claimName: odx-model-bscani-pv-claim
        - name: odx-model-bscani-volume
          emptyDir:
            medium: Memory
        - name: secrets-store-data-access
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: spc-data-access

---
apiVersion: v1
kind: Service
metadata:
  name: odx-model-internal-lb
  # CKV_K8S_21: "The default namespace should not be used"
  namespace: iaa
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: odx-model-bscani
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsubazuresb
  namespace: thinclientgroup
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      value: Endpoint=sb://sbnamespace-mlapi-dev-weus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=RtoV7Cb0Pj4TId/Sih+glpumtQRNPC6NadwOY3zGMfE=
    - name: lockDurationInSec
      value: 300
