apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.fullnameOverride }}-secret
data:
  ZEISS_USERNAME: {{ .Values.usecaseEnviromentSecrets.ZEISS_USERNAME | toString | b64enc }}
  ZEISS_PASSWORD: {{ .Values.usecaseEnviromentSecrets.ZEISS_PASSWORD | toString | b64enc }}
