from enum import Enum


class AIXSErrorCode(Enum):
    STORAGEQUERYEXCEPTIONERRORCODE = 100
    STORAGECLIENTINITEXCEPTIONERRORCODE = 101
    INFERENCERESULTSDATASTORAGEEXCEPTIONERRORCODE = 102
