apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
data:
  
  #CONFIG_HDP_SUBSCRIPTION_KEY_DEV_PLANNER: {{ .Values.envSecrets.CONFIG_HDP_SUBSCRIPTION_KEY_DEV_PLANNER | toString | b64enc }}
  #CONFIG_AZURE_TENANT_ID: {{ .Values.envSecrets.CONFIG_AZURE_TENANT_ID | toString | b64enc }}
  #CONFIG_AZURE_CLIENT_APP_ID: {{ .Values.envSecrets.CONFIG_AZURE_CLIENT_APP_ID | toString | b64enc }}
  #CONFIG_AZURE_SECRET: {{ .Values.envSecrets.CONFIG_AZURE_SECRET | toString | b64enc }}
  #CONFIG_APPREG_AIXS_S2S_HDP_CLIENT_SECRET_DEV_WEUS: {{ .Values.envSecrets.CONFIG_APPREG_AIXS_S2S_HDP_CLIENT_SECRET_DEV_WEUS | toString | b64enc }}
  #CONFIG_HDP_API_APP_ID: {{ .Values.envSecrets.CONFIG_HDP_API_APP_ID | toString | b64enc }}
  #CONFIG_HDP_TENANT_ID: {{ .Values.envSecrets.CONFIG_HDP_TENANT_ID | toString | b64enc }}
  #CONFIG_APPREG_AIXS_S2S_HDP_CLIENT_ID_DEV_WEUS: {{ .Values.envSecrets.CONFIG_APPREG_AIXS_S2S_HDP_CLIENT_ID_DEV_WEUS | toString | b64enc }}
  
  ##################
  CONFIG_AZURE_TENANT_ID: {{ .Values.envSecrets.CONFIG_AZURE_TENANT_ID | toString | b64enc }}
  CONFIG_AZURE_CLIENT_APP_ID: {{ .Values.envSecrets.CONFIG_AZURE_CLIENT_APP_ID | toString | b64enc }}
  CONFIG_AZURE_SECRET: {{ .Values.envSecrets.CONFIG_AZURE_SECRET | toString | b64enc }}
  CONFIG_HDP_API_APP_ID: {{ .Values.envSecrets.CONFIG_HDP_API_APP_ID | toString | b64enc }}
  CONFIG_HDP_TENANT_ID: {{ .Values.envSecrets.CONFIG_HDP_TENANT_ID | toString | b64enc }}
  CONFIG_HDP_SUBSCRIPTION_KEY_DEV_PLANNER: {{ .Values.envSecrets.CONFIG_HDP_SUBSCRIPTION_KEY_DEV_PLANNER | toString | b64enc }}
  CONFIG_HDP_AUTH_USERNAME: {{ .Values.envSecrets.CONFIG_HDP_AUTH_USERNAME | toString | b64enc }}
  CONFIG_HDP_AUTH_PWD: {{ .Values.envSecrets.CONFIG_HDP_AUTH_PWD | toString | b64enc }}
  CONFIG_HDP_AUTH_CLIENT: {{ .Values.envSecrets.CONFIG_HDP_AUTH_CLIENT | toString | b64enc }}
  CONFIG_SUBSCRIPTION_KEY: {{ .Values.envSecrets.CONFIG_SUBSCRIPTION_KEY | toString | b64enc }}
  CONFIG_HDP_SUBSCRIPTION_KEY: {{ .Values.envSecrets.CONFIG_HDP_SUBSCRIPTION_KEY | toString | b64enc }}
