apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-planner.fullname" . }}
  labels:
    {{- include "core-planner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "core-planner.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.servicePort  }}
    protocol: TCP
