apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "core-planner.fullname" . }}
  labels:
    {{- include "core-planner.labels" . | nindent 4 }}
  #automountServiceAccountToken: true
