testName: postapi_scenario_1
testPlan: testPlan.jmx
description: test the post request - 2 threads and 30s ramp up
engineInstances: 10
splitAllCSVs: False
failureCriteria:
- avg(response_time_ms) >  10000
- avg(requests_per_sec) >  10000
- avg(latency) >  10000
