trigger:
  branches:
    include:
      - 'develop'
  paths:
    include:
      - 'application/inference/client_keyvault/*'

jobs:
    - template: ../templates/artifacts/python-twine-publish-python-repo-template.yml
      parameters:
        artifactname: 'client_keyvault'