trigger:
  branches:
    include:
      - 'develop'
  paths:
    include:
      - 'application/inference/client_docker/*'

jobs:
    #
    # Publish code artifact and create test report
    #
    - template: ../templates/artifacts/python-twine-publish-python-repo-template.yml
      parameters:
        artifactname: 'client_docker'